"""
Django settings for odeme_test_app project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(5qiknu14$e0$0i59ht!&gnhdea$1x+j1^k^xx9_3s54-n+w2k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'odeme_test_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'odeme_test_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ödeme Sistemi Ayarları
# Gerçek projede bu bilgileri environment variables'dan alın!

# STRIPE AYARLARI
STRIPE_PUBLISHABLE_KEY = 'pk_test_...'  # Stripe Dashboard'dan alın
STRIPE_SECRET_KEY = 'sk_test_...'       # Stripe Dashboard'dan alın
STRIPE_WEBHOOK_SECRET = 'whsec_...'     # Webhook endpoint'i oluşturduktan sonra

# PAYPAL AYARLARI
PAYPAL_CLIENT_ID = 'YOUR_CLIENT_ID'     # PayPal Developer Dashboard'dan
PAYPAL_CLIENT_SECRET = 'YOUR_SECRET'    # PayPal Developer Dashboard'dan
PAYPAL_MODE = 'sandbox'  # 'sandbox' veya 'live'

# İYZICO AYARLARI
IYZICO_API_KEY = 'YOUR_API_KEY'         # İyzico Panel'den
IYZICO_SECRET_KEY = 'YOUR_SECRET_KEY'   # İyzico Panel'den
IYZICO_BASE_URL = 'https://sandbox-api.iyzipay.com'  # Test ortamı

# PAPARA AYARLARI
PAPARA_API_KEY = 'YOUR_API_KEY'         # Papara İş Yeri Paneli'nden
PAPARA_API_SECRET = 'YOUR_SECRET'       # Papara İş Yeri Paneli'nden

# SQUARE AYARLARI
SQUARE_APPLICATION_ID = 'YOUR_APP_ID'   # Square Developer Dashboard'dan
SQUARE_ACCESS_TOKEN = 'YOUR_TOKEN'      # Square Developer Dashboard'dan
SQUARE_ENVIRONMENT = 'sandbox'          # 'sandbox' veya 'production'

# RAZORPAY AYARLARI
RAZORPAY_KEY_ID = 'YOUR_KEY_ID'         # Razorpay Dashboard'dan
RAZORPAY_KEY_SECRET = 'YOUR_SECRET'     # Razorpay Dashboard'dan
