# Generated by Django 4.2.7 on 2025-08-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Rapor Başlığı')),
                ('excel_file', models.FileField(upload_to='reports/', verbose_name='Excel Dosyası')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Analiz Raporu',
                'verbose_name_plural': 'Analiz Raporları',
            },
        ),
    ]
