# Generated by Django 4.2.7 on 2025-08-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='excel_file',
            field=models.FileField(upload_to='', verbose_name='Excel Dosyası'),
        ),
    ]
